/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Landing from "../components/Landing";
import Navbar from "../components/Navbar";
import Partnerships from "../components/Partnerships";
import Apps from "../components/Apps";
import PartnerSection from "../components/PartnerSection";
import About from "../components/About";
import Links from "../components/Links";
import Immortalised from "../components/Immortalised";
import BVDLabs from "../components/BVDLabs";
import Team from "../components/Team";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>BVDCity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-bg">
        <Navbar />
        <Landing />
        <Apps />
        <Partnerships />
        <PartnerSection />
        <About />
        <Links />
        <Immortalised />
        <BVDLabs />
        <Team />
        <Footer />
      </main>
    </>
  );
}
